# Generated by Django 4.2.2 on 2023-06-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='name_of_medication',
        ),
    ]
