# Generated by Django 4.2.2 on 2023-06-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_remove_medication_name_of_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='name_of_medication',
            field=models.CharField(default='', max_length=64),
        ),
    ]
