# Generated by Django 4.2.2 on 2023-06-12 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_alter_capacity_capacity_alter_capacity_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='capacity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medications.capacity'),
        ),
    ]
