# Generated by Django 4.2.2 on 2023-06-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0008_alter_medication_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ml'), (3, 'dose'), (2, 'pills'), (1, 'mg')], default=0),
        ),
    ]
