# Generated by Django 4.2.2 on 2023-06-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0011_medication_capacity_unit_alter_capacity_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='capacity_unit',
        ),
        migrations.DeleteModel(
            name='Capacity',
        ),
    ]
