# Generated by Django 4.2.2 on 2023-06-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0012_remove_medication_capacity_unit_delete_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('unit', models.PositiveSmallIntegerField(choices=[(2, 'pills'), (0, 'ml'), (3, 'dose'), (1, 'mg')], default=0)),
            ],
        ),
    ]
