# Generated by Django 4.2.2 on 2023-06-12 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0013_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='capacity_amount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medications.capacity'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ml'), (1, 'mg'), (2, 'pills'), (3, 'dose')], default=0),
        ),
    ]
