# Generated by Django 4.2.2 on 2023-06-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0014_medication_capacity_amount_alter_capacity_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='capacity_amount',
            new_name='capacity_unit',
        ),
        migrations.RemoveField(
            model_name='capacity',
            name='amount',
        ),
        migrations.AlterField(
            model_name='capacity',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ml'), (1, 'mg'), (3, 'dose'), (2, 'pills')], default=0),
        ),
    ]
