# Generated by Django 4.2.2 on 2023-06-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0015_rename_capacity_amount_medication_capacity_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='unit',
            field=models.CharField(choices=[('ml', 'milliliters'), ('dose', 'dose'), ('mg', 'milligrams'), ('pills', 'pills')], max_length=10),
        ),
    ]
