# Generated by Django 4.2.2 on 2023-06-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0016_alter_capacity_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='capacity_unit',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='start_date',
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='times_per_day',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='unit',
            field=models.CharField(choices=[('pills', 'pills'), ('mg', 'mg'), ('dose', 'dose'), ('ml', 'ml')], default='ml', max_length=10),
        ),
        migrations.DeleteModel(
            name='Capacity',
        ),
    ]
