# Generated by Django 4.2.2 on 2023-06-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0018_remove_medication_times_per_day_medication_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='hour',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='medication',
            name='unit',
            field=models.CharField(choices=[('dose', 'dose'), ('pills', 'pills'), ('ml', 'ml'), ('mg', 'mg')], default='ml', max_length=10),
        ),
    ]
