# Generated by Django 4.2.2 on 2023-06-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0019_rename_hour_medication_time_alter_medication_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='unit',
            field=models.CharField(choices=[('mg', 'mg'), ('ml', 'ml'), ('pcs', 'pcs'), ('dose', 'dose')], default='ml', max_length=10),
        ),
    ]
