# Generated by Django 4.2.2 on 2023-06-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0020_alter_medication_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='dosage',
            new_name='dosage1',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='time',
            new_name='time1',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='unit',
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage2',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage3',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='time2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='time3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='unit1',
            field=models.CharField(choices=[('mg', 'mg'), ('dose', 'dose'), ('pcs', 'pcs'), ('ml', 'ml')], default='ml', max_length=10),
        ),
        migrations.AddField(
            model_name='medication',
            name='unit2',
            field=models.CharField(choices=[('mg', 'mg'), ('dose', 'dose'), ('pcs', 'pcs'), ('ml', 'ml')], default='ml', max_length=10),
        ),
        migrations.AddField(
            model_name='medication',
            name='unit3',
            field=models.CharField(choices=[('mg', 'mg'), ('dose', 'dose'), ('pcs', 'pcs'), ('ml', 'ml')], default='ml', max_length=10),
        ),
    ]
