# Generated by Django 4.2.2 on 2023-06-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0021_rename_dosage_medication_dosage1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='dosage1',
            new_name='dosage_1',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='dosage2',
            new_name='dosage_2',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='dosage3',
            new_name='dosage_3',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='time1',
            new_name='time_1',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='time2',
            new_name='time_2',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='time3',
            new_name='time_3',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='unit1',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='unit2',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='unit3',
        ),
        migrations.AddField(
            model_name='medication',
            name='unit_1',
            field=models.CharField(choices=[('pcs', 'pcs'), ('dose', 'dose'), ('ml', 'ml'), ('mg', 'mg')], default='ml', max_length=10),
        ),
        migrations.AddField(
            model_name='medication',
            name='unit_2',
            field=models.CharField(choices=[('pcs', 'pcs'), ('dose', 'dose'), ('ml', 'ml'), ('mg', 'mg')], default='ml', max_length=10),
        ),
        migrations.AddField(
            model_name='medication',
            name='unit_3',
            field=models.CharField(choices=[('pcs', 'pcs'), ('dose', 'dose'), ('ml', 'ml'), ('mg', 'mg')], default='ml', max_length=10),
        ),
    ]
