# Generated by Django 4.2.2 on 2023-06-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0022_rename_dosage1_medication_dosage_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='unit_1',
            field=models.CharField(choices=[('mg', 'mg'), ('dose', 'dose'), ('ml', 'ml'), ('pcs', 'pcs')], default='ml', max_length=10),
        ),
        migrations.AlterField(
            model_name='medication',
            name='unit_2',
            field=models.CharField(choices=[('mg', 'mg'), ('dose', 'dose'), ('ml', 'ml'), ('pcs', 'pcs')], default='ml', max_length=10),
        ),
        migrations.AlterField(
            model_name='medication',
            name='unit_3',
            field=models.CharField(choices=[('mg', 'mg'), ('dose', 'dose'), ('ml', 'ml'), ('pcs', 'pcs')], default='ml', max_length=10),
        ),
    ]
