# Generated by Django 4.2.2 on 2023-06-29 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0023_alter_medication_unit_1_alter_medication_unit_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='time_1',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='time_2',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='time_3',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='unit_1',
            field=models.CharField(choices=[('ml', 'ml'), ('mg', 'mg'), ('dose', 'dose'), ('pcs', 'pcs')], default='ml', max_length=10),
        ),
        migrations.AlterField(
            model_name='medication',
            name='unit_2',
            field=models.CharField(choices=[('ml', 'ml'), ('mg', 'mg'), ('dose', 'dose'), ('pcs', 'pcs')], default='ml', max_length=10),
        ),
        migrations.AlterField(
            model_name='medication',
            name='unit_3',
            field=models.CharField(choices=[('ml', 'ml'), ('mg', 'mg'), ('dose', 'dose'), ('pcs', 'pcs')], default='ml', max_length=10),
        ),
    ]
