# Generated by Django 4.2.2 on 2023-06-29 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0024_alter_medication_time_1_alter_medication_time_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='time_1',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medication',
            name='time_2',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medication',
            name='time_3',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medication',
            name='unit_1',
            field=models.CharField(choices=[('ml', 'ml'), ('dose', 'dose'), ('mg', 'mg'), ('pcs', 'pcs')], default='ml', max_length=10),
        ),
        migrations.AlterField(
            model_name='medication',
            name='unit_2',
            field=models.CharField(choices=[('ml', 'ml'), ('dose', 'dose'), ('mg', 'mg'), ('pcs', 'pcs')], default='ml', max_length=10),
        ),
        migrations.AlterField(
            model_name='medication',
            name='unit_3',
            field=models.CharField(choices=[('ml', 'ml'), ('dose', 'dose'), ('mg', 'mg'), ('pcs', 'pcs')], default='ml', max_length=10),
        ),
    ]
