# Generated by Django 4.2.2 on 2023-06-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0026_remove_medication_dosage_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dose',
            name='slug',
            field=models.SlugField(default='1', max_length=250),
        ),
        migrations.AlterField(
            model_name='dose',
            name='unit',
            field=models.CharField(choices=[('mg', 'mg'), ('dose', 'dose'), ('pcs', 'pcs'), ('ml', 'ml')], default='ml', max_length=10),
        ),
    ]
