# Generated by Django 4.2.2 on 2023-06-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0027_dose_slug_alter_dose_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dose',
            name='unit',
            field=models.CharField(choices=[('mg', 'mg'), ('ml', 'ml'), ('dose', 'dose'), ('pcs', 'pcs')], default='ml', max_length=10),
        ),
    ]
