# Generated by Django 4.2.2 on 2023-06-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0028_alter_dose_slug_alter_dose_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='unit',
            field=models.CharField(choices=[('pcs', 'pcs'), ('mg', 'mg'), ('dose', 'dose'), ('ml', 'ml')], default='ml', max_length=10),
        ),
    ]
