# Generated by Django 4.2.2 on 2023-06-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0029_alter_dose_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dose',
            name='slug',
        ),
        migrations.AddField(
            model_name='medication',
            name='slug',
            field=models.SlugField(default=' ', max_length=250),
        ),
        migrations.AlterField(
            model_name='dose',
            name='unit',
            field=models.CharField(choices=[('ml', 'ml'), ('mg', 'mg'), ('dose', 'dose'), ('pcs', 'pcs')], default='ml', max_length=10),
        ),
    ]
